# Introduction to Probability? {#intro}

## What is probability?

## Why probability? 

## How probability works? 

### Important Terms

### Permutation and Combination

Suppose, we have three letters: A, B, and C. If we are told to take two of them and arrange them in as many ways as possible, we could write:

AB
BA
AC
CA
BC
CA

We can arrange them in 6 different ways. Here, AB and BA are different arrangements. 

Consider a row of a train with two seats. 

### Playing Cards

#### Concept of Playing Cards

#### Problems

i. Problem

3 cards are drawn from a pack of 52 cards. What is the probability that they are all Kings?

**Solution:**

There are 4 Kings. We've to draw 3 cards.

$P(K) =\frac{^4C_3}{{^52}C_3}$

ii. Problem

If a card is drawn from a deck of 52 cards with 4 aces, what is the probability that an ace will not show up? 

**Solution:**

Let, P(A) = Ace appears 

 Now, $P(A)=\frac 4 {52}= \frac{1}{13}$
 
 $\therefore$ the probability that an ace will not show up is  $1 - P(A) = 1-\frac 1 {13}$ = `r round(1-1/3,2)`
 
iii. Problem

Two cards are drawn with replacement; What is the probability that they are

i. Kings of same color
ii. Kings of different color
iii. Not Kings at all
 
**Solution:**

i. $P(BUR) =P(B)+P(R)$
$\frac{^2C_1 \times ^2C_1}{^{52}C_1\times ^{52}C_1}+\frac{^2C_1 \times ^2C_1}{^{52}C_1\times ^{52}C_1}$ Why not $^{52}C_2$, $^4C_2$

ii. $1-P(B \cup R)$
$P(K)= \frac{^4C_1 \times ^4C_1}{^{52}C_1\times ^{52}C_1}$

iv. Problem

A card is drawn from a pack of 52 cards. What is the probability that it is

i. an Ace
ii. A Spade
iii. A Hearts or a King

**Solution:**
